# Generated by Django 5.0.2 on 2024-03-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=200, verbose_name='Категория')),
                ('category_slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('category_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop_app.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('category_slug', 'category_parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('product_slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('product_brand', models.CharField(max_length=200, verbose_name='Бренд')),
                ('product_price', models.IntegerField(verbose_name='Цена')),
                ('product_desc', models.TextField(max_length=2000, verbose_name='Описание')),
                ('product_image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('product_available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('product_stock', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_app.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-product_created',),
                'index_together': {('id', 'product_slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_app.product',),
        ),
    ]
